focal_point: [0.0, 0.0, -0.445]

front_plane_dimensions: [0.4, 0.3]
front_plane_center_location: [0.0, 0.2, -0.295]

front_plane_distance: 0.2
rear_plane_distance: 0.55

object_dimensions: [0.1, 0.1, 0.1]

object1_position: [0.0, 0.3, -0.3675]
object2_position: [-0.1, 0.3, -0.3825]
object3_position: [0.15, 0.3, -0.3825]
object4_position: [0.05, 0.4, -0.3825]

lar_block_dimensions: [0.085, 0.087, 0.155]
med_block_dimensions: [0.09, 0.05, 0.140]
sma_block_dimensions: [0.045, 0.045, 0.045]


goal_object_position: [0.025, 0.45, -0.4225]

frequency: 100