front_plane_dimensions: [0.4, 0.3]
front_plane_distance: 0.2
rear_plane_distance: 0.45

object_dimensions: [0.1, 0.1, 0.1]
object1_position: [0.055, 0.25, 0.05]
object2_position: [-0.16, 0.25, 0.05]
object3_position: [-0.05, 0.25, 0.05]
frequency: 100